### ISSUE TITLE
Add pink box around "Get Tickets"

### ISSUE THREAD

**Issue by jenrobbins** [artifactconf/artifactconf2019-www#17]
For more attention.

**Comment by teleject** [comment]
There is already a pink box around Get Tickets. Or do you mean something else?

![Screen Shot 2019-04-13 at 2 56 28 PM](https://user-images.githubusercontent.com/41737/56084694-5de5e500-5dfc-11e9-9e28-b7f0b130937b.png)

**Comment by jenrobbins** [comment]
On the menu on the left side of the Home Page.
