### ISSUE TITLE
Create Scholarships information page

### ISSUE THREAD

**Issue by aristiles** [artifactconf/artifactconf2019-www#18]
Please note, this page should be linked from the footer menu, with the label "scholarships." It will link from other areas of the site where contextually appropriate, and I'll submit those as separate issues. Also, I wasn't sure about where you'd place this in the hierarchy, so I just did absolute links. Please don't kill me ded.

To be safe, here are two links to the application form in case one acts flaky
short: https://forms.gle/zS3ychBC7UdxtAdFA
full size: https://docs.google.com/forms/d/e/1FAIpQLSedizHdSZw-_blEZk7M2U3RR9z2b64LLfOF1rTQA8MHA2y0Uw/viewform?usp=sf_link

ready, set, go:

### ARTIFACT Diversity Scholarships
We are pleased to offer the first-ever ARTIFACT Diversity Scholarship to attendees from tech’s most underrepresented populations. We have always had an inclusive conference, so it is only natural to diversify our attendee pool in the effort to be even more inclusive.  It is our goal to remove the financial and logistical obstacles that make conference attendance difficult or even impossible for some.

Applications and scholarship offers will remain anonymous, and we will do what we can to make offers in a timely manner. See the timeline below to get some idea what to expect regarding communication. 

Those selected will receive assistance to attend ARTIFACT Conference, September 29 & October 1, 2019 at the Alamo Drafthouse South Lamar in Austin, Texas. All recipients are expected to abide by our Conference Code of Conduct and the Alamo Drafthouse Code of Conduct.

**Potential Diversity Scholarship Offerings**
Please keep in mind we have a very limited number of tickets and funds to disburse, so we probably won’t be able to accommodate every applicant. We’ll prioritize applications based on when they were received (read: the earlier the better) and the clarity of the applicants’ stated needs.

Types of aid available:

- Discounted or free tickets to ARTIFACT Conference
- Financial assistance with travel
- Financial assistance with accommodations
- Financial assistance with evening meals during the conference (breakfast and lunch are served at the conference)

Unavailable at this time:

- Discounts or free tickets for Wednesday workshops
- Childcare

**Eligibility**
Criteria for eligibility includes, but is not limited to: people of color, indigenous persons, people with disabilities, those who identify as LGBTQIA+, people 55 or older, veterans or new graduates just starting their careers, women, full-time students, those who work for nonprofit, government, or educational institutions with limited resources, and the unemployed.

Applications will be reviewed, and if we are unable to verify your eligibility, we will let you know within five business days. Please be aware that applications containing false information will be disqualified.

**Diversity Scholarship Timeline:**

- Applications are due before June 1, 2019.
- Confirmed receipt of application will be emailed within  two business days of your application
- We’ll let you know if there are problems with your application or omissions within five business days of your application.
- Anonymous judging of applications happens during the month of June.
- Scholarship offers sent via email starting July 1, 2019
- Scholarship recipients will have five business days to accept or refuse offers
- Refused offers will be passed along to the next applicant on our waiting list
- No new scholarship offers will be made after August 15, 2019

**Ready to apply?**
Head on over to <a href=”https://forms.gle/zS3ychBC7UdxtAdFA”>fill out our application form</a>. We’ll confirm receipt of your application within two business days.

**Help us build a more diverse conference**
The ARTIFACT Community has always been inclusive. By contributing to our Scholarship Fund, you make it even better! Anyone can participate—<a href=”https://artifactconf.com/tickets/”>just head over to our tickets page to make a donation</a>. 

Or maybe you are hoping to contribute on a larger scale? Maybe diversity is a high priority in your team or organization and you want everyone to have the same great experiences you have? Contact <a href="mailto:stiles@artifactconf.com">Ari Stiles</a> if you’d like to sponsor our Diversity Scholarships in a big way.

**Questions and feedback** 
This is our first year offering Diversity Scholarships, so we know there will be room for improvement. Contact <a href="mailto:stiles@artifactconf.com">Ari Stiles</a> with questions about the program or suggestions on how to make it better.

**Comment by aristiles** [comment]
okay, in both of the mailto: links on this page (note, they are in the last two paragraphs), I put the wrong email address. should be ari@artifactconf.com

**Comment by teleject** [comment]
Done.
