### ISSUE TITLE
Change diversity description on site/ticket descriptions

### ISSUE THREAD

**Issue by aristiles** [artifactconf/artifactconf2019-www#3]
Diversity Scholarship
We’ve set aside some tickets for attendees from tech’s most underrepresented populations. Some transportation and accommodation funds might be available too! Details and an application form will go live on April 16, 2019. Join our mailing list (link to form? or just say"below"?) to be one of the first to know when Diversity Scholarship information becomes available.

**Comment by aristiles** [comment]
Once the scholarship page is up, can you change that 'graf to read:

We’ve set aside some tickets and are working on financial assistance for attendees from tech’s most underrepresented populations. Get the details on our <a href="LINK TO GROOVY NEW SCHOLARSHIPS PAGE">Scholarships page</a>. Applications are due before June 1, 2019.

**Comment by teleject** [comment]
Done.
