### ISSUE TITLE
Updating Scholarship deadlines on the site

### ISSUE THREAD

**Issue by aristiles** [artifactconf/artifactconf2019-www#47]
Hey, I changed our submission form to reflect the new Diversity Scholarship deadline, but there are a few pages on the site that will need updating as well:

On https://artifactconf.com/tickets/
Please change "Applications are due before June 1, 2019." to "Applications are due before June 15, 2019."

and

On https://artifactconf.com/scholarships/
Please change "Applications are due before June 1, 2019." to "Applications are due before June 15, 2019."

Thanks!

**Comment by jenrobbins** [comment]
I'll try to do this, but the last time I tried, I don't have permission to change the site. I'll get it set up and Christopher can push it through.

**Comment by jenrobbins** [comment]
I've made the code changes. They just need to be merged and published.

**Comment by aristiles** [comment]
Hi hi—since we are extending again, the same pages/places will need to change again. So:

On https://artifactconf.com/tickets/
Please change "Applications are due before June 15, 2019." to "Applications are due before June 21, 2019."

and

On https://artifactconf.com/scholarships/
Please change "Applications are due before June 15, 2019." to "Applications are due before June 21, 2019."

I already changed the google form to reflect the new dates.

Thanks!
