### ISSUE TITLE
Tweaks to Schedule Page(s)

### ISSUE THREAD

**Issue by aristiles** [artifactconf/artifactconf2019-www#48]
I spent some time poking around on the site today checking on content issues, and noticed a couple of things about the schedule page(s):
https://artifactconf.com/schedule/day1/
https://artifactconf.com/schedule/day2/

1.) Can we make the footer menu items match the other pages on the site? Specifically, "Scholarships" ( https://artifactconf.com/scholarships/ ) appears as a menu choice in the footer of all the other pages between "Code of Conduct" and "Terms of Service". It would be great to have the same link on both schedule pages.

2.) We can toggle between day one and day two at the top of the pages, but not at the bottom, which means users need to scroll all the way to the top again to switch days. This is particularly problematic on mobile devices, since we scroll through several screens to get to the bottom. It would be nice to have a toggle at the bottom, too, or even just a link to the other day's schedule. We have an amazing lineup and I don't want visitors to miss it!

Thanks,
--Ari

**Comment by danmall** [comment]
> Can we make the footer menu items match the other pages on the site? Specifically, "Scholarships" ( https://artifactconf.com/scholarships/ ) appears as a menu choice in the footer of all the other pages between "Code of Conduct" and "Terms of Service". It would be great to have the same link on both schedule pages.

Yep! Sorry for that oversight (the only downside to a completely static site that doesn't use includes).

> It would be nice to have a toggle at the bottom, too, or even just a link to the other day's schedule. We have an amazing lineup and I don't want visitors to miss it!

Coming up!
